### ISSUE TITLE
GitHub Campus Advisor Program Next Steps

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-jifbrodeur#11]
👋 Hello @jifbrodeur, your Campus Advisor training needs updates to assignment modules [2.2](https://github.com/Campus-Advisors/campus-advisor-training-jifbrodeur/issues/6) and [4](https://github.com/Campus-Advisors/campus-advisor-training-jifbrodeur/issues/10). Please complete those and we'll be happy to process your request for certification.

Once you have re-submitted the assignment, please reapply for the GitHub Campus Advisor program at https://airtable.com/shr6ZHMoHOb9kBupY

**Comment by jifbrodeur** [comment]
Hi, I resubmitted, I think I am all good now 😊
Thanks
Jean-François
